port = 8080
name = "worker"
batch = 500000
queue_worker = 20
queue_ethereum = 20
queue_elastic = 20
dispatchers = 1

[ethereum]
url = "http://localhost:8545"
contract = "0x42699A7612A82f1d9C36148af9C77354759b210b"
primary_key = "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63"

[elastic]
url = "http://localhost:9200"
username = "elastic"
password = "changeme"
