port = 8080
name = "worker"
batch = 100
queue_worker = 1_000
queue_ethereum = 1_000
queue_elastic = 1_000
dispatchers = 1

[ethereum]
url = "http://localhost:8545"
contract = "0x2F632b08EcE7E9DcA0fCff1F91c1D5Bc245440Eb"
primary_key = "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63"

[elastic]
url = "http://localhost:9200"
username = "elastic"
password = "changeme"
