global:
  scrape_interval: 1ms

scrape_configs:
  - job_name: audita-worker
    scrape_interval: 1ms
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:8080
