{
 "title": "Monitoring auditaserver",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(logs_total[$__interval]))",
     "legendFormat": "logs/s"
    }
   ]
  },
  {
   "title": "Worker queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "avg(logs_queue)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Elastic queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    { "expr": "avg(elastic_queue)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ethereum queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "avg(ethereum_queue)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App ERROR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/audita.log\"} | detected_level = `error`"
    }
   ]
  },
  {
   "title": "App INFO",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/audita.log\"} | detected_level != `error`"
    }
   ]
  }
 ]
}